Repository trinodb/trino-python-client, pull requests merged in 2022-11, with the labels that each got.

#267 [sqlalchemy] Improve the performance of TrinoDialect.get_view_names
  tests/integration/test_sqlalchemy_integration.py
  trino/sqlalchemy/dialect.py
Labels: cla-signed

#272 Add 0.319.0 release notes
  CHANGES.md
Labels: cla-signed, release-notes

#281 Support `None` values in array, map and row types
  tests/integration/test_types_integration.py
  trino/client.py
Labels: cla-signed

#146 Add release pipeline
  .github/workflows/release.yml
Labels: cla-signed, no-release-notes

#284 Fix refresh tokens flow
  tests/unit/oauth_test_utils.py
  tests/unit/test_client.py
  trino/auth.py
Labels: cla-signed

#288 Bump GH actions version
  .github/workflows/ci.yml
Labels: cla-signed, no-release-notes

#208 [mypy] Enforce Mypy checks for a subset of modules
  .pre-commit-config.yaml
  setup.cfg
  trino/client.py
  trino/exceptions.py
  trino/logging.py
  trino/transaction.py
Labels: cla-signed
